version: '3.3'

volumes:
  postgres_data:
  static_data:
  media_data:
  redoc:

services:
  db:
    image: postgres:13.0-alpine
    container_name: foodgram-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${DB_NAME}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: demetrius2017/foodgram_backend
    container_name: foodgram-backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_data:/app/backend_static/
      - media_data:/app/foodgram/media/
      - redoc:/app/docs/

  frontend:
    image: demetrius2017/foodgram_frontend
    container_name: foodgram_frontend
    volumes:
       - frontend_data:/static/
    command: cp -r /app/build/. /static/
    depends_on:
      - backend

  nginx:
    image: demetrius2017/foodgram_gateway
    container_name: foodgram_gateway
    ports:
      - 9000:80
    volumes:
      - static_data:/usr/share/nginx/html/static_backend/
      - frontend_data:/usr/share/nginx/html/
      - media_data:/usr/share/nginx/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
