version: '3.3'

volumes:
  postgres_data:
  static_data:
  media_data:
  redoc:

services:
  db:
    image: postgres:13.0-alpine
    container_name: foodgram-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: demetrius2017/foodgram_backend
    container_name: foodgram-backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_data:/backend_static/static/
      - media_data:/app/media
      - redoc:/app/api/docs/

  frontend:
    image: demetrius2017/foodgram_frontend
    container_name: foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: demetrius2017/foodgram_gateway
    container_name: foodgram_gateway
    ports:
      - 9000:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - static_data:/var/html/static/
      - media_data:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
